
 FROM maven:3.9.8-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn -q -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/consumer-service-0.0.1-shaded.jar app.jar
EXPOSE 8081
ENV KAFKA_BOOTSTRAP_SERVERS=localhost:9092
ENTRYPOINT ["java","-jar","app.jar"]
